/**
 * Generate docs/EVIDENCE.md from docs/evidence.json and inventory/issued.json.
 *
 *   npm run evidence-doc      (run automatically at the end of `npm run evidence`)
 *
 * Generated rather than hand-written, so a hash in the documentation cannot drift
 * from the hash on chain. Edit this script, not the Markdown.
 */

import { readFileSync, statSync, writeFileSync } from "node:fs";

import { CONTRACT_ID, NETWORK_PASSPHRASE, explorer } from "../src/lib/config";
import { fatal, log, readJson } from "./lib/cli";

const WASM_PATH = "contracts/target/wasm32v1-none/release/quietstay_rights.wasm";
const TEST_PATH = "contracts/quietstay-rights/src/test.rs";

/** Read facts rather than restate them, so the document cannot drift from the code. */
function contractFacts(): { tests: number; wasmBytes: number | null } {
  const tests = (readFileSync(TEST_PATH, "utf8").match(/^#\[test\]$/gm) ?? []).length;
  let wasmBytes: number | null = null;
  try {
    wasmBytes = statSync(WASM_PATH).size;
  } catch {
    // Not built in this checkout; the row is omitted rather than guessed.
  }
  return { tests, wasmBytes };
}

interface EvidenceFile {
  contract: string;
  accounts: { issuer: string; owner: string; renter: string; buyer: string };
  rights_issued_for_this_run: Record<string, { right_id: number; commitment: string; issue_tx: string }>;
  transactions: {
    id: string;
    title: string;
    what: string;
    expected: string;
    right_id: number;
    hash: string;
    successful: boolean;
    reached_ledger: boolean;
    failure?: string;
    explorer: string;
  }[];
}

interface IssuedFile {
  issuer: string;
  rights: {
    right_id: number;
    record_file: string;
    canonical_file: string;
    commitment: string;
    attestation_file: string;
    attested: boolean;
    issue_tx: string;
    week: { check_in: string; check_out: string; use_year: number };
    bedrooms: number;
  }[];
}

function main(): void {
  const evidence: EvidenceFile = readJson("docs/evidence.json");
  const issued: IssuedFile = readJson("inventory/issued.json");

  const byId = (id: string) => evidence.transactions.find((t) => t.id === id);
  const rental = byId("rental");
  const sale = byId("sale");
  const noApproval = byId("rejected-no-approval");
  const seizure = byId("rejected-seizure");

  const { tests, wasmBytes } = contractFacts();

  const txRow = (item: EvidenceFile["transactions"][number] | undefined): string => {
    if (!item) return "| _(not produced)_ | | | |";
    const verdict = item.successful ? "succeeded" : "**rejected by the contract**";
    return `| ${item.title} | ${verdict} | [\`${item.hash.slice(0, 16)}…\`](${item.explorer}) | ${
      item.reached_ledger ? "yes" : "**no**"
    } |`;
  };

  const doc = `# Evidence

Everything a reviewer needs, as links to open. No cloning, no building, no command
line. Generated by \`npm run evidence\` — the hashes below came back from the network,
they were not typed in.

- [Deliverable 1 — the contract](#deliverable-1--soroban-smart-contracts)
- [Deliverable 2 — verification and selective disclosure](#deliverable-2--verifiable-ownership-and-selective-disclosure)
- [Deliverable 3 — the reference application](#deliverable-3--reference-web-application)
- [Reproducing all of it](#reproducing-all-of-it)

---

## Deliverable 1 — Soroban smart contracts

| | |
| --- | --- |
| **Network** | \`${NETWORK_PASSPHRASE}\` (testnet) |
| **Contract address** | [\`${CONTRACT_ID}\`](${explorer.contract()}) |
| **Explorer** | ${explorer.contract()} |
| **Source** | [\`contracts/quietstay-rights/src/\`](../contracts/quietstay-rights/src/) |
| **Tests** | [\`src/test.rs\`](../contracts/quietstay-rights/src/test.rs) — ${tests} tests, \`cd contracts && cargo test\` |${
    wasmBytes === null
      ? ""
      : `\n| **WASM size** | ${wasmBytes.toLocaleString("en-US")} bytes (limit 65,536) |`
  }

The transfer design is one primitive with a duration parameter: an open-ended
transfer is a sale, a transfer carrying an expiry is a rental, and there is no
second code path. See [DESIGN.md](./DESIGN.md#the-transfer-primitive).

Tests that matter most, by name:

| Test | What it pins down |
| --- | --- |
| \`a_rental_lapses_with_no_return_transaction\` | A term ends on its own; nobody sends anything. |
| \`a_lapsed_renter_cannot_transfer_the_week_on\` | A renter whose term ended is not the holder and is rejected. |
| \`a_lapsed_renter_cannot_list_or_burn_the_week\` | The same, for every other action. |
| \`a_transfer_needs_both_the_holder_and_the_issuer\` | Holder alone fails; issuer alone fails; both succeed. |
| \`the_issuer_cannot_seize_a_held_right\` | The centralization condition, in a unit test. |
| \`the_issuer_cannot_seize_a_right_that_is_out_on_rental\` | Neither title nor occupancy is reachable. |
| \`the_issuer_cannot_burn_a_holders_right\` | No destruction path for the issuer either. |
| \`an_approval_is_bound_to_the_exact_terms_it_was_given_for\` | An approval cannot be redirected to another recipient or term. |
| \`a_renter_cannot_sell_what_they_only_rent\` | No grant may outlast the grantor's own term. |
| \`the_title_holder_cannot_sell_over_an_active_rental\` | A renter cannot be sold out from under. |

## Deliverable 2 — Verifiable ownership and selective disclosure

### The four transactions

Two succeed, two are refused. All four were included in a ledger, which is what makes
the refusals evidence rather than assertions — a transaction the network turns away at
submission leaves nothing to open.

| What | Outcome | Transaction | On ledger |
| --- | --- | --- | --- |
${txRow(rental)}
${txRow(sale)}
${txRow(noApproval)}
${txRow(seizure)}

**The two required hashes**, stated plainly:

- Transfer **with** issuer approval, succeeds: [\`${sale?.hash ?? "—"}\`](${sale?.explorer ?? ""})
- Transfer **without** issuer approval, rejected by the contract: [\`${noApproval?.hash ?? "—"}\`](${noApproval?.explorer ?? ""})

Both are the same transfer of the same right by the same holder. The only difference
is the issuer's authorization entry. ${
    noApproval?.failure ? `The contract's refusal: _${noApproval.failure}_` : ""
  }

### The centralization condition

The reviewer's condition on approval was that issuer-approved transfers must not let
the issuer seize or freeze anything. This transaction is the issuer attempting exactly
that — building, signing, and paying for a transfer of a held right to itself:

**[\`${seizure?.hash ?? "—"}\`](${seizure?.explorer ?? ""})** — rejected by the contract.

The issuer can supply its own approval; it cannot supply the holder's authorization,
which \`transfer\` requires independently. See
[DESIGN.md § centralization](./DESIGN.md#centralization-what-the-issuer-can-and-cannot-do)
for the enumerated privileged surface and an honest account of what a malicious issuer
can still do.

### What the explorer shows

Verified by fetching each transaction back from the network and searching the raw
bytes of the envelope, the result, and the meta for every value in the off-chain
records — \`npm run check-privacy\`. Nothing was assumed.

**Never present:** owner name, email, resort name, country, unit, deed reference,
registry, record id, salt, or any fee figure.

The successful **sale** transaction's contract call, decoded in full:

\`\`\`
transfer(
  from       = "${evidence.accounts.owner}"
  to         = "${evidence.accounts.buyer}"
  right_id   = ${sale?.right_id ?? "—"}
  expires_at = null        // a sale carries no timestamp at all
)
\`\`\`

and its event: topics \`["transfer", <from>, <to>]\`, data
\`{ commitment: 0x…, expires_at: null, right_id: … }\`.

A hash and account addresses. That is the whole of it.

Two things *are* public, deliberately, and are documented rather than glossed over:
the week's date range lives in contract state because an offer has to say what it is
offering, and a rental's term-end timestamp is in the call because the contract cannot
enforce a term it cannot see. Neither is attached to any identity. Full accounting in
[DESIGN.md § what the ledger reveals](./DESIGN.md#what-the-ledger-reveals).

### A sample attestation

[\`inventory/attestations/right-1.attestation.json\`](../inventory/attestations/right-1.attestation.json)
— issuer-signed, bound to right #1, this contract, and this network. Schema, signing
input, and the eleven-step verification procedure are in
[ATTESTATION.md](./ATTESTATION.md).

Also included on purpose: [\`right-4.attestation.json\`](../inventory/attestations/right-4.attestation.json),
which asserts \`maintenance_fees_current: false\`. Sample week 04 carries €410 in
arrears, so the issuer attests that it is **not** clean. Verifying right #4 fails on
exactly that check, and the approval service declines to approve a transfer of it —
while the holder keeps the week, because declining is not seizing.

### Sample inventory

| Right | Week | Attested clean | Commitment | Record |
| --- | --- | --- | --- | --- |
${issued.rights
  .map(
    (r) =>
      `| #${r.right_id} | ${r.week.check_in} → ${r.week.check_out} | ${
        r.attested ? "yes" : "**no — arrears**"
      } | \`${r.commitment.slice(0, 16)}…\` | [\`${r.record_file.split("/").pop()}\`](../${r.record_file}) |`,
  )
  .join("\n")}

Each commitment is reproducible with \`sha256sum\` alone —
see [COMMITMENT.md](./COMMITMENT.md#reproducing-a-commitment).

## Deliverable 3 — Reference web application

Four screens, connected to the deployed contract:

| Screen | What it does |
| --- | --- |
| [Issue](../src/app/issue/page.tsx) | Commit to an ownership record and create the right. The commitment is computed in the browser, so the hash is never a surprise from a server. |
| [List](../src/app/list/page.tsx) | The registry as the contract has it: holder, term, standing offers. |
| [Verify](../src/app/verify/page.tsx) | A counterparty checks a disclosed record and attestation, entirely client-side. |
| [Transfer](../src/app/transfer/page.tsx) | Rent or sell through one form, with issuer approval — plus a control that submits **without** approval so the refusal can be watched. |

Running it: [SETUP.md](./SETUP.md). Demo walkthrough: [DEMO_SCRIPT.md](./DEMO_SCRIPT.md).

End-to-end test against the running app — SEP-10, issuance, offers, an approved
rental, a refused unapproved transfer, a declined approval, and an attempted
impersonation:

\`\`\`
npm run build && npm run start     # one terminal
npm run e2e                        # another → 24 checks
\`\`\`

## Accounts used

| Role | Account |
| --- | --- |
| Issuer | [\`${evidence.accounts.issuer}\`](${explorer.account(evidence.accounts.issuer)}) |
| Owner | [\`${evidence.accounts.owner}\`](${explorer.account(evidence.accounts.owner)}) |
| Renter | [\`${evidence.accounts.renter}\`](${explorer.account(evidence.accounts.renter)}) |
| Buyer | [\`${evidence.accounts.buyer}\`](${explorer.account(evidence.accounts.buyer)}) |

## Reproducing all of it

\`\`\`bash
cd contracts && cargo test          # 32 unit tests
./scripts/deploy.sh                 # build, test, deploy to testnet
npm run seed                        # issue the sample inventory, write attestations
npm run evidence                    # produce the four transactions above
npm run check-privacy               # confirm nothing leaked, against the real chain
npm run verify-record -- 3 inventory/records/week-03.json inventory/attestations/right-3.attestation.json
\`\`\`

\`npm run evidence\` issues its own weeks each time rather than reusing the sample
inventory, because a sale is permanent and reusing them would make the script work
exactly once. Re-running it appends rights to the registry and rewrites this document.

---

_Generated ${"by `npm run evidence`"} from \`docs/evidence.json\`. Do not edit by hand._
`;

  writeFileSync("docs/EVIDENCE.md", doc, "utf8");
  log.ok("wrote docs/EVIDENCE.md");
}

try {
  main();
} catch (error) {
  fatal(error);
}
